[package]
name = "slider"
version = "0.3.0"
authors = ["Pierre Chevalier <pierrechevalier83@hotmail.fr>"]

[dependencies]
gfx_device_gl = "0.9.0"
find_folder = "0.3.0"
image = "0.9"
piston_window = "0.42.0"
rand="0.3.14"
