[package]
name = "slider"
version = "0.3.0"
authors = ["Pierre Chevalier <pierrechevalier83@hotmail.fr>"]

[dependencies]
gfx_device_gl = "*"
find_folder = "*"
image = "*"
piston_window = "*"
rand="*"
